### PR TITLE
Switch away from console.log

### PR DESCRIPTION
**Pull request by bas-ie**
This is after the introduction to Tape, so there shouldn't be too much of a problem with using it here instead of console statements.

### CODE REVIEW

**Comment by richchurcher** [comment]
Er, by 'it' I mean `test.equal` sry! :sunglasses:

**Comment by mixmix** [comment]
I think this work as long as you're careful how you set up test. I.e. the following would be really confusing / break  

```js
test('adder', function(test) {
  test.equal(adder(2,3), 5, 'can add positive numbers are')
  test.end()
} 
```

I like what you've done with using `test` instead of `t`  , but there's a convention in all our work to use : `var test = require('tape')`  which could get confusing unless you change them all.

**Comment by mixmix** [comment]
I think this is a good short term solution :)

I just tell a story about `t` being a testing toolbox thingy ...
Merge away

**Comment by locksmithdon** [comment]
`{% raw %}` was a really good find. I couldn't find it when I was struggling with this. 

:+1:

**Comment by richchurcher** [comment]
Note: I mistakenly added to this PR when intending to create a new one. Don has reviewed: just switching some formatting.

**Pull request merged**
