### PR TITLE
flat structure + hyphens

### PR DESCRIPTION
**Pull request by simontegg**
This is a breaking change. Merging this break the git books that reference this repo.

This branch enforces a `-` hyphen naming convention for files. 
It also changes it to a maximum of 1 level of nesting inside topic folders. 
A few files are shifted around

### CODE REVIEW

**Comment by locksmithdon** [comment]
Looks like a file slipped through the cracks:
```
server-side/api/client_server_bank.png → api/client_server_bank.png
```

**Comment by simontegg** [comment]
When do cohort facilitators want to bite the bullet and have this merged in? @Rosie-Brigham @mixmix. 

Do you want me to go through your cohort books and prep pull requests that switch them over to this new config?

**Comment by locksmithdon** [comment]
I'm happy for this to be merged ASAP, but of course Kauri hasn't started yet, so this is more Roo's call than anyone IMO.

**Comment by locksmithdon** [comment]
@Rosie-Brigham I'm about to start building Kauri's book and I'd like to build it against the changes in this PR. I'm happy to fix the links in Roa's book and submit them as a single commit if that makes your life easier (since this PR will break links). Just give me the go.

**Comment by Rosie-Brigham** [comment]
@locksmithdon  I'm happy fix everything, but can I leave it until tomorrow afternoon?

**Comment by locksmithdon** [comment]
That's fine @Rosie-Brigham. Let me know if I can help. Thanks!

**Pull request merged**
